# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
