# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20170517_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insert',
            options={'get_latest_by': 'push_date'},
        ),
    ]
