# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20170517_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
