# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_remove_team_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.CharField(choices=[('AP', 'Access Point Setup'), ('AD', 'Android App Dev'), ('SS', 'Server Setup'), ('UI', 'User Interface')], default='AP', max_length=2),
        ),
    ]
